name = "@web-speed-hackathon/leaderboard"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

[miniflare]
env_path = ".env"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"
